In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
digits=load_digits()

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)

In [29]:
lr=LogisticRegression(max_iter=100000)
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9666666666666667

In [30]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9861111111111112

In [31]:
rf=RandomForestClassifier(n_estimators=50)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9722222222222222

In [32]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [33]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [34]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [37]:
get_score(LogisticRegression(max_iter=100000),x_train,x_test,y_train,y_test)

0.9666666666666667

In [40]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [46]:
scores_l=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
    digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=100000),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=50),x_train,x_test,y_train,y_test))
    

In [47]:
scores_l

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [48]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [49]:
scores_rf

[0.9265442404006677, 0.9532554257095158, 0.9165275459098498]

In [50]:
from sklearn.model_selection import cross_val_score

In [52]:
cross_val_score(LogisticRegression(max_iter=100000),digits.data,digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [53]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [54]:
cross_val_score(RandomForestClassifier(n_estimators=100),digits.data,digits.target)

array([0.93333333, 0.925     , 0.9637883 , 0.9637883 , 0.91643454])